# Assignment 2 - DS4Biz Y63
## TextScraping_Classification
***

### Team Detail
**Team Name**: woonoh 
***
### *Student 1*
**Student ID**: 61070313
**Student Full Name**: XXXXXXX XXXXXXXX
***
### *Student 2*
**Student ID**: 61070323   
**Student Full Name**: XXXXXXX XXXXXXXX
***

In [9]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [10]:
response = requests.get('https://quotes.toscrape.com/')
soup = BeautifulSoup(response.content)

In [11]:
links = []
for page in range(1,11):
    if page == 1: 
        url = "http://quotes.toscrape.com"
    else: 
        url = "http://quotes.toscrape.com/page/"+str(page)
    links.append(url)

In [12]:
from bs4 import BeautifulSoup
import requests
tt = []
    #print(url)
for linkk in links:
    page = requests.get(linkk)
    soup = BeautifulSoup(page.content, 'html.parser')
    #quotes = soup.find_all('div', class_='quote')
    
    for q in soup.find_all("div", {"class":"quote"}):
        dictt = {}
        dictt['quote'] = q.find('span', class_='text').text
        dictt['author'] = q.find('small', class_='author').text
        dictt['tags'] = [tag.text for tag in q.find_all("a",{"class":"tag"})]
        tt.append(dictt)


    
#news_archive_list_link_news = []
#testlink = 'http://www.it.kmitl.ac.th/~teerapong/news_archive/month-jan-2017.html'

In [13]:
quote_all= []
for linkk in links:
    page = requests.get(linkk)
    soup = BeautifulSoup(page.content, 'html.parser')
    #quotes = soup.find_all('div', class_='quote')
    
    for q in soup.find_all("div", {"class":"quote"}):
        dictt = {}
        dictt['quote'] = q.find('span', class_='text').text
        #dictt[author] = q.find('small', class_='author').text
        #dictt['tags'] = [tag.text for tag in q.find_all("a",{"class":"tag"})]
        quote_all.append(dictt)

In [14]:
dff = pd.DataFrame(tt)
#print(dff) #complete

In [15]:
dff.columns

Index(['quote', 'author', 'tags'], dtype='object')

In [16]:
#dff = dff.set_axis(['quote', 'author', 'tags'], axis=1, inplace=False)

In [17]:
import pandas
from sklearn.preprocessing import MultiLabelBinarizer


# Binarise labels
mlb = MultiLabelBinarizer()
expandedLabelData = mlb.fit_transform(dff["tags"])
labelClasses = mlb.classes_


# Create a pandas.DataFrame from our output
expandedLabels = pandas.DataFrame(expandedLabelData, columns=labelClasses)

In [18]:
expandedLabels

,abilities,activism,adulthood,adventure,age,alcohol,aliteracy,apathy,attributed,attributed-no-source,...,unhappy-marriage,value,wander,wisdom,women,world,write,writers,writing,yourself
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
expandedLabels.dtypes

abilities    int32
activism     int32
adulthood    int32
adventure    int32
age          int32
             ...
world        int32
write        int32
writers      int32
writing      int32
yourself     int32
Length: 137, dtype: object

In [20]:
expandedLabels.to_csv('datastore\expandedLabels.csv', index = False)

In [21]:
drop_dff = dff.drop(['tags','quote'], axis=1)
drop_dff

                author
0      Albert Einstein
1         J.K. Rowling
2      Albert Einstein
3          Jane Austen
4       Marilyn Monroe
..                 ...
95          Harper Lee
96   Madeleine L'Engle
97          Mark Twain
98           Dr. Seuss
99  George R.R. Martin

[100 rows x 1 columns]

In [22]:
data1 = pd.concat([drop_dff, expandedLabels], axis=1)

In [23]:
#data

---------------------------------

In [24]:
Content = dff['quote']

In [25]:
text_list =Content

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction import text
stopwords = text.ENGLISH_STOP_WORDS
tokenize = CountVectorizer().build_tokenizer()
all_filtered_tokens = []
for doc in text_list:
    # tokenize the next document
    tokens = tokenize(doc.lower())
    # remove the stopwords
    filtered_tokens = []  
    for token in tokens:
        if not token in stopwords:
            filtered_tokens.append(token)
    filtered_tokens = ' '.join(filtered_tokens)
    # add to the overall list
    all_filtered_tokens.append(filtered_tokens)
print("Created %d filtered token lists" % len(all_filtered_tokens) )

Created 100 filtered token lists

In [27]:
all_filtered_tokens

['world created process thinking changed changing thinking',
 'choices harry truly far abilities',
 'ways live life miracle miracle',
 'person gentleman lady pleasure good novel intolerably stupid',
 'imperfection beauty madness genius better absolutely ridiculous absolutely boring',
 'try man success man value',
 'better hated loved',
 'failed ve just 10 000 ways won work',
 'woman like tea bag know strong hot water',
 'day sunshine like know night',
 'life make matter going mess universal truth good decide going mess girls friends ll act like just remember come ones stay true best friends don let remember sisters make best friends world lovers ll come baby hate say actually pretty going break heart ll soulmate ll half makes goes just fail doesn mean gonna fail trying hold believe don sweetie head high chin importantly smiling life beautiful thing smile',
 'takes great deal bravery stand enemies just stand friends',
 'explain year old don understand',
 'loved love loves matters perfect aren perfect make laugh cause think twice admit human making mistakes hold thinking second day knows break heart don hurt don change don analyze don expect smile makes happy let know makes mad miss',
 'like nonsense wakes brain cells fantasy necessary ingredient living',
 'gone intended think ended needed',
 'opposite love hate indifference opposite art ugliness indifference opposite faith heresy indifference opposite life death indifference',
 'lack love lack friendship makes unhappy marriages',
 'good friends good books sleepy conscience ideal life',
 'life happens making plans',
 'love knowing love simply problems pride love way know way loving intimate hand chest hand intimate fall asleep eyes close',
 'minute angry lose seconds happiness',
 'judge people time love',
 'thinks sitting church make christian think sitting garage make car',
 'beauty eye beholder necessary time time stupid misinformed beholder black eye',
 'today truer true alive youer',
 'want children intelligent read fairy tales want intelligent read fairy tales',
 'impossible live failing unless live cautiously lived case fail default',
 'logic imagination',
 'good thing music hits feel pain',
 'read things know learn places ll',
 'course happening inside head harry earth mean real',
 'truth going hurt just got ones worth suffering',
 'great things small things great love',
 'organized mind death great adventure',
 'need love little chocolate doesn hurt',
 'read know',
 'fool know point understand',
 'imagined paradise kind library',
 'late',
 'reader lives thousand lives dies said jojen man reads lives',
 'cup tea large book long suit',
 'believe lies eventually learn trust',
 'make woman laugh make',
 'life like riding bicycle balance moving',
 'real lover man thrill kissing forehead smiling eyes just staring space',
 'wise girl kisses doesn love listens doesn believe leaves left',
 'darkness stars',
 'matters born grow',
 'love does begin end way think does love battle love war love growing',
 'really friends notion loving people halves nature',
 'thing day scares',
 'good angel sin devil just small girl big world trying love',
 'physicist probably musician think music live daydreams music life terms music',
 'read books reading think thinking',
 'difference genius stupidity genius limits',
 'like drug bella',
 'friend loyal book',
 'door happiness closes opens look long closed door opened',
 'life isn finding life creating',
 'problem drinking thought poured drink bad happens drink attempt forget good happens drink order celebrate happens drink make happen',
 'don forget face person hope',
 'remember madly love right kiss anytime feel like',
 'love vulnerable love heart wrung possibly broken want make sure keeping intact animal wrap carefully round hobbies little luxuries avoid entanglements lock safe casket coffin selfishness casket safe dark motionless airless change broken unbreakable impenetrable irredeemable love vulnerable',
 'wander lost',
 'pity dead harry pity living live love',
 'writing sit typewriter bleed',
 'finish day blunders absurdities doubt crept forget soon tomorrow new day shall begin serenely high spirit encumbered old nonsense',
 'let schooling interfere education',
 'heard troubles kind come ahead come ve bought big bat ready troubles going troubles',
 'flower time thought walk garden forever',
 'people crazy truly horrible lives lead',
 'trouble having open mind course people insist coming trying things',
 'think left think right think low think high oh thinks think try',
 'really knocks book reading wish author wrote terrific friend phone felt like doesn happen',
 'reason talk answers accept',
 'say dreamer hope someday ll join world live',
 'free prejudice hate equally',
 'question isn going let going stop',
 'classic book people praise don read',
 'mistake tried new',
 'lady imagination rapid jumps admiration love love matrimony moment',
 'remember time come make choice right easy remember happened boy good kind brave strayed path lord voldemort remember cedric diggory',
 'declare enjoyment like reading sooner tires thing book house shall miserable excellent library',
 'people really love fewer think world dissatisfied day confirms belief inconsistency human characters little dependence placed appearance merit sense',
 'day old start reading fairy tales',
 'necessarily doubting god best wondering painful best turn',
 'fear death follows fear life man lives fully prepared die time',
 'lie travel half way world truth putting shoes',
 'believe christianity believe sun risen',
 'truth dumbledore sighed beautiful terrible thing treated great caution',
 'got die time die let live life way want',
 'die awfully big adventure',
 'takes courage grow really',
 'better hurt truth comforted lie',
 'really understand person consider things point view climb inside skin walk',
 'write book wants written book difficult grown ups write children',
 'tell truth people worthy',
 'person person matter small',
 'mind needs books sword needs whetstone edge']

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english",min_df = 5)
tfidf_matrix = vectorizer.fit_transform(all_filtered_tokens)
feature_names = vectorizer.get_feature_names()
dense = tfidf_matrix.todense()
denselist = dense.tolist()

In [29]:
df = pd.DataFrame(denselist, columns=feature_names)
df

,book,day,don,good,just,know,let,life,like,live,love,make,people,read,really,thing,think,time,truth,world
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.659278,0.0,0.751899,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,1.0,0.0,0.0,0.0,0.000000,0.0
96,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.693882,0.0,0.0,0.0,0.0,0.0,0.720088,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0
99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Create the Document Term Matrix
count_vectorizer = CountVectorizer(stop_words='english')
count_vectorizer = CountVectorizer()
sparse_matrix = count_vectorizer.fit_transform(all_filtered_tokens)

# OPTIONAL: Convert Sparse Matrix to Pandas Dataframe if you want to see the word frequencies.
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, 
                  columns=count_vectorizer.get_feature_names())
df

,000,10,abilities,absolutely,absurdities,accept,act,actually,admiration,admit,...,worth,worthy,wrap,write,writing,written,wrote,wrung,year,youer
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,1,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Visualize Existing Data

-----------------------------------

In [31]:
df_quote = pd.DataFrame(all_filtered_tokens)
df_quote = df_quote.set_axis(['quote'], axis=1, inplace=False)

In [32]:
df_quote.dtypes

quote    object
dtype: object

In [33]:
df_quote

                                                quote
0   world created process thinking changed changin...
1                   choices harry truly far abilities
2                      ways live life miracle miracle
3   person gentleman lady pleasure good novel into...
4   imperfection beauty madness genius better abso...
..                                                ...
95  really understand person consider things point...
96  write book wants written book difficult grown ...
97                           tell truth people worthy
98                         person person matter small
99        mind needs books sword needs whetstone edge

[100 rows x 1 columns]

In [34]:
#choose top 15 tags
test = expandedLabels.sum(axis=0).sort_values(ascending=False)
test.head(15)

love                    14
life                    13
inspirational           13
humor                   12
books                   11
reading                  7
friendship               5
truth                    4
friends                  4
attributed-no-source     3
death                    3
simile                   3
writing                  3
philosophy               2
paraphrased              2
dtype: int64

In [35]:
top15 = expandedLabels[['love','life','inspirational','humor','books','reading','friendship','truth','friends','attributed-no-source','death','simile','writing','philosophy','paraphrased']]

In [38]:
top15

,love,life,inspirational,humor,books,reading,friendship,truth,friends,attributed-no-source,death,simile,writing,philosophy,paraphrased
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0
4,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
96,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
97,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
98,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
99,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [39]:
data1 = pd.concat([drop_dff,top15], axis=1)

In [40]:
data = pd.concat([df_quote,data1], axis=1)
data.dtypes

quote                   object
author                  object
love                     int32
life                     int32
inspirational            int32
humor                    int32
books                    int32
reading                  int32
friendship               int32
truth                    int32
friends                  int32
attributed-no-source     int32
death                    int32
simile                   int32
writing                  int32
philosophy               int32
paraphrased              int32
dtype: object

In [41]:
data

,quote,author,love,life,inspirational,humor,books,reading,friendship,truth,friends,attributed-no-source,death,simile,writing,philosophy,paraphrased
0,world created process thinking changed changin...,Albert Einstein,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,choices harry truly far abilities,J.K. Rowling,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,ways live life miracle miracle,Albert Einstein,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0
3,person gentleman lady pleasure good novel into...,Jane Austen,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0
4,imperfection beauty madness genius better abso...,Marilyn Monroe,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,really understand person consider things point...,Harper Lee,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
96,write book wants written book difficult grown ...,Madeleine L'Engle,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0
97,tell truth people worthy,Mark Twain,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
98,person person matter small,Dr. Seuss,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
99,mind needs books sword needs whetstone edge,George R.R. Martin,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

----------------------------------------------

## Multi-Label-Text-Classification

In [86]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(data,random_state=42, test_size=0.10, shuffle=True)
#train, test = train_test_split(data)
#print(train.shape)
#print(test.shape)

In [87]:
train_text = train['quote']
test_text = test['quote']

In [88]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(strip_accents='unicode', analyzer='word', ngram_range=(1,3), norm='l2')
vectorizer.fit(train_text)
vectorizer.fit(test_text)

TfidfVectorizer(ngram_range=(1, 3), strip_accents='unicode')

In [89]:

X_train = vectorizer.transform(train_text)
y_train = train.drop(labels = ['quote','author'], axis=1)

X_test = vectorizer.transform(test_text)
y_test = test.drop(labels = ['quote','author'], axis=1)

In [90]:
test_text

83    declare enjoyment like reading sooner tires th...
53    physicist probably musician think music live d...
70              flower time thought walk garden forever
45    real lover man thrill kissing forehead smiling...
44              life like riding bicycle balance moving
39                                                 late
22                               judge people time love
80                                    mistake tried new
10    life make matter going mess universal truth go...
0     world created process thinking changed changin...
Name: quote, dtype: object

In [91]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(strip_accents='unicode', analyzer='word', ngram_range=(1,3), norm='l2')
vectorizer.fit(train_text)
vectorizer.fit(test_text)

TfidfVectorizer(ngram_range=(1, 3), strip_accents='unicode')

In [92]:

X_train = vectorizer.transform(train_text)
Y_train = train.drop(labels = ['quote','author'], axis=1)

X_test = vectorizer.transform(test_text)
Y_test = test.drop(labels = ['quote','author'], axis=1)

In [93]:
X_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

## OneVsRestClassifier

from sklearn.multiclass import OneVsRestClassifier
from sklearn.datasets import make_multilabel_classification
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

classifier = OneVsRestClassifier(SVC(kernel='linear'))

results = cross_val_score(classifier, X_train, y_train, cv=loocv)

print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

In [158]:

from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC



model_to_set = OneVsRestClassifier(SVC(kernel="poly"))

parameters = {
    "estimator__C": [1,2,4,8],
    "estimator__kernel": ["poly","rbf"],
    "estimator__degree":[1, 2, 3, 4],
}

model_tunning = GridSearchCV(model_to_set, param_grid=parameters)

model_tunning.fit(X_train, y_train)

print(model_tunning.best_score_)
print(model_tunning.best_params_) #เอา

0.36666666666666664
{'estimator__C': 1, 'estimator__degree': 1, 'estimator__kernel': 'rbf'}

## RandomForestClassifier

In [95]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import LeaveOneOut
#Create a Gaussian Classifier
classifier=RandomForestClassifier()

loocv = LeaveOneOut()

results = cross_val_score(classifier, X_train, y_train, cv=loocv)

print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))
#เอา

Accuracy: 33.333% (47.140%)

In [157]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [2, 3, 14, 40],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [20, 40, 60, 100]
}
# Create a based model
rf = RandomForestRegressor()


model_tunning = GridSearchCV(rf, param_grid=param_grid)

model_tunning.fit(X_train, y_train)

print(model_tunning.best_score_)
print(model_tunning.best_params_)

-0.01837265519548234
{'bootstrap': True, 'max_depth': 2, 'max_features': 3, 'min_samples_leaf': 3, 'min_samples_split': 8, 'n_estimators': 20}

## ClassifierChain

In [103]:
from skmultilearn.problem_transform import ClassifierChain
from sklearn.linear_model import LogisticRegression

loocv = LeaveOneOut()
# initialize classifier chains multi-label classifier
classifierChain = ClassifierChain(LogisticRegression())

results = cross_val_score(classifierChain, X_train, y_train, cv=loocv)

print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))
#เอา

Accuracy: 33.333% (47.140%)

In [161]:
from skmultilearn.problem_transform import ClassifierChain
from sklearn.model_selection import GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

parameters = [
    {
        'classifier': [MultinomialNB()],
        'classifier__alpha': [0.7, 1.0],
    },
    {
        'classifier': [SVC()],
        'classifier__kernel': ['rbf', 'linear'],
    },
]

clf = GridSearchCV(ClassifierChain(), parameters, scoring='accuracy')


model_tunning = GridSearchCV(clf, param_grid=parameters)

model_tunning.fit(X_train, y_train)

print(model_tunning.best_score_)
print(model_tunning.best_params_)

ValueError: Invalid parameter classifier for estimator GridSearchCV(estimator=ClassifierChain(require_dense=[True, True]),
             param_grid=[{'classifier': [MultinomialNB()],
                          'classifier__alpha': [0.7, 1.0]},
                         {'classifier': [SVC()],
                          'classifier__kernel': ['rbf', 'linear']}],
             scoring='accuracy'). Check the list of available parameters with `estimator.get_params().keys()`.

In [104]:

from skmultilearn.problem_transform import LabelPowerset
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import cross_val_score
classifier = LabelPowerset(LogisticRegression())
loocv = LeaveOneOut()
classifier.fit(X_train, y_train)

results = cross_val_score(classifier, X_train, y_train, cv=loocv)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))
#เอา

Accuracy: 32.222% (46.733%)

In [ ]:
from skmultilearn.adapt import MLkNN
classifier.fit(X_train, y_train)
classifier = LabelPowerset(LogisticRegression())
results = cross_val_score(classifier, X_train, y_train, cv=loocv)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))
#เอา

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    "estimator__n_estimators": [5, 50, 100],
  "estimator__max_depth" : [None, 10,20],
  "estimator__min_samples_split" : [2, 5, 10],
}
# Create a based model
rf = RandomForestRegressor()


model_tunning = GridSearchCV(rf, param_grid=param_grid)

model_tunning.fit(X_train, y_train)

print(model_tunning.best_score_)
print(model_tunning.best_params_)

In [ ]:
"estimator__n_estimators": [5, 50, 200],
  "estimator__max_depth" : [None, 10,20],
  "estimator__min_samples_split" : [2, 5, 10],

In [133]:
best = grid_search.best_score_ * 100
print(best)

-2.710119724687431

In [69]:

from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score
from sklearn.multiclass import OneVsRestClassifier

# Using pipeline for applying logistic regression and one vs rest classifier
LogReg_pipeline = Pipeline([
                ('clf', OneVsRestClassifier(LogisticRegression(solver='sag'), n_jobs=-1)),
            ])

for tags in categories:
    print('-Processing {}'.format(tags))
    
    # Training logistic regression model on train data
    LogReg_pipeline.fit(X_train, train[tags])
    
    # calculating test accuracy
    prediction = LogReg_pipeline.predict(X_test)
    print('Test accuracy is {}'.format(accuracy_score(test[tags], prediction)))
    print("\n")

-Processing love
Test accuracy is 0.7


0.0
-Processing life
Test accuracy is 0.8


0.0
-Processing inspirational
Test accuracy is 0.8


0.0
-Processing humor
Test accuracy is 1.0


0.0
-Processing books
Test accuracy is 0.9


0.0
-Processing reading
Test accuracy is 0.9


0.0
-Processing friendship
Test accuracy is 0.9


0.0
-Processing truth
Test accuracy is 1.0


0.0
-Processing friends
Test accuracy is 0.9


0.0
-Processing attributed-no-source
Test accuracy is 0.9


0.0
-Processing death
Test accuracy is 1.0


0.0
-Processing simile
Test accuracy is 0.9


0.0
-Processing writing
Test accuracy is 1.0


0.0
-Processing philosophy
Test accuracy is 1.0


0.0
-Processing paraphrased
Test accuracy is 1.0


0.0

In [ ]:
print(X)

------------------